export const FETCH_PRODUCT_VARIANTS_REQUEST = "FETCH_PRODUCT_VARIANTS_REQUEST";
export const FETCH_PRODUCT_VARIANTS_SUCCESS = "FETCH_PRODUCT_VARIANTS_SUCCESS";
export const FETCH_PRODUCT_VARIANTS_FAILED = "FETCH_PRODUCT_VARIANTS_FAILED";
