export const FETCH_CATEGORIES_REQUEST = "FETCH_CATEGORIES_REQUEST";
export const FETCH_CATEGORIES_SUCCESS = "FETCH_CATEGORIES_SUCCESS";
export const FETCH_CATEGORIES_FAILED = "FETCH_CATEGORIES_FAILED";

export const FETCH_FEATURED_CATEGORIES_REQUEST =
  "FETCH_FEATURED_CATEGORIES_REQUEST";
export const FETCH_FEATURED_CATEGORIES_SUCCESS =
  "FETCH_FEATURED_CATEGORIES_SUCCESS";
export const FETCH_FEATURED_CATEGORIES_FAILED =
  "FETCH_FEATURED_CATEGORIES_FAILED";
