export const FETCH_PRODUCT_BANNER_REQUEST = "FETCH_PRODUCT_BANNER_REQUEST";
export const FETCH_PRODUCT_BANNER_SUCCESS = "FETCH_PRODUCT_BANNER_SUCCESS";
export const FETCH_PRODUCT_BANNER_FAILED = "FETCH_PRODUCT_BANNER_FAILED";
