export const FETCH_PRODUCTS_REQUEST = "FETCH_PRODUCTS_REQUEST";
export const FETCH_PRODUCTS_SUCCESS = "FETCH_PRODUCTS_SUCCESS";
export const FETCH_PRODUCTS_FAILED = "FETCH_PRODUCTS_FAILED";

export const FETCH_FEATURED_PRODUCTS_REQUEST =
  "FETCH_FEATURED_PRODUCTS_REQUEST";
export const FETCH_FEATURED_PRODUCTS_SUCCESS =
  "FETCH_FEATURED_PRODUCTS_SUCCESS";
export const FETCH_FEATURED_PRODUCTS_FAILED = "FETCH_FEATURED_PRODUCTS_FAILED";

export const FETCH_BRAND_PRODUCTS_REQUEST = "FETCH_BRAND_PRODUCTS_REQUEST";
export const FETCH_BRAND_PRODUCTS_SUCCESS = "FETCH_BRAND_PRODUCTS_SUCCESS";
export const FETCH_BRAND_PRODUCTS_FAILED = "FETCH_BRAND_PRODUCTS_FAILED";

export const FETCH_PRODUCT_FILTERS_REQUEST = "FETCH_PRODUCT_FILTERS_REQUEST";
export const FETCH_PRODUCT_FILTERS_SUCCESS = "FETCH_PRODUCT_FILTERS_SUCCESS";
export const FETCH_PRODUCT_FILTERS_FAILED = "FETCH_PRODUCT_FILTERS_FAILED";
