export const FETCH_LATEST_PRODUCTS_REQUEST = "FETCH_LATEST_PRODUCTS_REQUEST";
export const FETCH_LATEST_PRODUCTS_SUCCESS = "FETCH_LATEST_PRODUCTS_SUCCESS";
export const FETCH_LATEST_PRODUCTS_FAILED = "FETCH_LATEST_PRODUCTS_FAILED";
