export const FETCH_LATEST_PRODUCTS_REQUEST = "FETCH_LATEST_PRODUCTS_REQUEST";
export const FETCH_LATEST_PRODUCTS_SUCCESS = "FETCH_LATEST_PRODUCTS_SUCCESS";
export const FETCH_LATEST_PRODUCTS_FAILED = "FETCH_LATEST_PRODUCTS_FAILED";

export const FETCH_PRODUCTS_BY_CATEGORY_REQUEST =
  "FETCH_PRODUCTS_BY_CATEGORY_REQUEST";
export const FETCH_PRODUCTS_BY_CATEGORY_SUCCESS =
  "FETCH_PRODUCTS_BY_CATEGORY_SUCCESS";
export const FETCH_PRODUCTS_BY_CATEGORY_FAILED =
  "FETCH_PRODUCTS_BY_CATEGORY_FAILED";
